### ISSUE TITLE
Let CallError inherit from Throwable

### ISSUE THREAD

**Issue by fabian-kotschenreuther** [grandcentrix/grandcentrix-kotlin-either#18]
Good morning,

does it make sense to let `CallError` inherit from `Throwable`?
This could be used to implement a successOrThrow method, for example.

**Comment by lukasz-kalnik-gcx** [comment]
A `Throwable` is a very special type in Java which basically is intended for throwing. The point of `CallError` is completely the opposite - to avoid throwing and pass everything inside one data type.
`CallError` has to wrap `Throwable` because this is what it gets from Retrofit if a call fails. But `CallError` **is not** a throwable, that's why it should not extend it.

Can you show an example code where it could be beneficial?

**Comment by fabian-kotschenreuther** [comment]
After a short telephone conversation we came to the conclusion that we will not install this.
More detailed information on request^^.
